---
# ansible/roles/homebrew/tasks/main.yml
# Install Homebrew packages

- name: Check Homebrew availability
  command: which brew
  register: brew_check
  ignore_errors: true
  changed_when: false

- name: Install Homebrew if missing
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    executable: /bin/bash
  environment:
    CI: '1'
    NONINTERACTIVE: '1'
  become: true
  register: brew_install
  when: brew_check.rc != 0
  changed_when: brew_install.rc == 0

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
    path: /opt/homebrew/bin
  loop: "{{ homebrew_packages }}"

# Workaround: avoid sudo password prompt during Docker cask installation
- name: Create Docker cask directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: staff
    mode: '0755'
  loop:
    - /usr/local/bin
    - /usr/local/cli-plugins
  when: "'docker' in homebrew_cask_apps"

- name: Install Homebrew cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_cask_apps }}"
