blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/kumo01GitHub/setup-mac/discussions
    about: Please ask and answer questions in GitHub Discussions.
