---
# ansible/roles/vscode_extensions/defaults/main.yml

# Keep defaults empty by design.
# Add optional extensions via ansible/custom.yml using
# vscode_extensions_list_extra.
vscode_extensions_list:
  []
